update_calss_name = {{'125bis', {'class_1st_half': 'barely', 'class_2nd_half': 'potato'}},
                     'A39', {'class_1st_half': 'barely', 'class_2nd_half': 'potato'},
                     'A39', {'class_1st_half': 'barely', 'class_2nd_half': 'potato'},
                     'D1', {'class_1st_half': 'barely', 'class_2nd_half': 'empty'},
                     'D10', {'class_1st_half': 'barely', 'class_2nd_half': 'empty'},
                     'D13', {'class_1st_half': 'barely', 'class_2nd_half': 'empty'},
                     'D14', {'class_1st_half': 'barely', 'class_2nd_half': 'empty'},
                     'D2', {'class_1st_half': 'barely', 'class_2nd_half': 'empty'},
                     'D9', {'class_1st_half': 'barely', 'class_2nd_half': 'empty'},


                     '132E', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     '5A', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'A21', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'A26', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'B6', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'B7', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'B8', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'C40', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D15', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D16', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D17', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D18', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D23', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D24', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D26', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D5', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D6', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D7', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'D8',  {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'E36',  {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     'E65', {'class_1st_half': 'wheat', 'class_2nd_half': 'empty'},
                     }
